# Basic nodejs workflow
name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          # cache: 'npm'
      - run: |
          npm ci
          npm build --if-present
          npm stylelint
      # - run: npm run test
